version: "3.3"
networks:
  rtsp-server:

services:
  rtsp_server:
    image: aler9/rtsp-simple-server
    networks:
      - rtsp-server
    ports:
      - ${RTSP_PORT}:8554
      - 1935:1935 
    environment:
      - RTSP_PROTOCOLS=tcp
  stream:
    container_name: ${STREAM_ENDPOINT}
    image: baicontainers/rtsp-feed
    networks:
      - rtsp-server
    volumes:
      - ${VOLUME_MOUNT}
    depends_on:
      - rtsp_server 
    environment:
      - STREAM_ENDPOINT=${STREAM_ENDPOINT}
      - FILE_PATH=${FILE_PATH}
